# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: MERGE TO MASTER

permissions:
  id-token: write

on:
  push:
    branches:
      - main

env:
  TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.TENANT_ID }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
  OBJECT_ID: ${{ secrets.OBJECT_ID }}
  WEBAPP_NAME: "achievers-webapp"
  SLOT_NAME: "stg"
  RESOURCE_GROUP: "achievers-rg"

jobs:
  e2etests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: achievers
      DB_USER: root
      DB_PASSWORD: my-secret-pw

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
          MYSQL_EXTRA_FLAGS: "--lower-case-table-names=1"
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Set up test DB
        run: mysql -h 127.0.0.1 --port 3306 -u ${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        env:
          DATABASE_URL: mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@127.0.0.1:3306/${{ env.DB_DATABASE }}
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Migrate test DB
        env:
          DATABASE_URL: mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@127.0.0.1:3306/${{ env.DB_DATABASE }}
        run: npm run setup

      - name: Install E2E
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        env:
          DATABASE_URL: mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@127.0.0.1:3306/${{ env.DB_DATABASE }}
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: |
            playwright-report/
            coverage/
          retention-days: 1

  migrate:
    name: Migrate and seed production DB
    runs-on: ubuntu-latest
    needs: e2etests
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Migrate DB
        run: npm run setup

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: migrate

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run semantic-release

  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: duvet86/achievers-app:latest, duvet86/achievers-app:${{ steps.package-version.outputs.current-version}}

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e4f1458d614f40f5947f467bb0e3f8a0 }}
          images: duvet86/achievers-app:latest

  swap-slots:
    name: Swap slots
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap slots
        run: az webapp deployment slot swap -s ${{ env.SLOT_NAME }} -n ${{ env.WEBAPP_NAME }} -g ${{ env.RESOURCE_GROUP }}
